### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Xingwd** [Xingwd/loggingx#1]
**Version:** 1.0.0

**描述:**

使用fastapi写的api服务。

> 以下配置和操作，在python>=3.9环境中可以正常运行，但是在python<=3.8环境中会报错。

日志配置：

``` python
LOGGING_CONFIG = {
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
      'verbose': {
         'format': '%(asctime)s.%(msecs)03d %(levelname)-8s %(processName)s:%(threadName)s %(pathname)s:%(lineno)d - %(message)s',
         'datefmt': '%Y-%m-%d %H:%M:%S'
      },
      'simple': {
         'format': '{name:s}: {asctime:s} {levelname} {message}',
         'style': '{',
         'datefmt': '%Y-%m-%d %H:%M:%S'
      },
   },
   'handlers': {
      'console': {
         'class': 'logging.StreamHandler',
         'level': 'INFO',
         'formatter': 'simple'
      },
      'redis_stream': {
         'class': 'loggingx.handlers.RedisStreamHandler',
         'level': 'INFO',
         'redis_url': 'redis://redis:6379/0'
      }
   },
   'loggers': {
      'cloud': {
         'handlers': ['console'],
         'propagate': True,
      },
      'cloud.request': {
         'handlers': ['redis_stream'],
         'level': 'INFO',
         'propagate': True,
      }
    },
}
```

启动命令：

``` shell
uvicorn app.main:app
```

启动报错如下：

``` text
Traceback (most recent call last):
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/logging/config.py", line 388, in resolve
    found = getattr(found, frag)
AttributeError: module 'loggingx' has no attribute 'handlers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/logging/config.py", line 721, in configure_handler
    klass = self.resolve(cname)
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/loggingx/handlers.py", line 49, in <module>
    class RedisStreamListener(QueueListener):
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/loggingx/handlers.py", line 88, in RedisStreamListener
    def dequeue(self, block) -> Union[dict[bytes, bytes], None]:
TypeError: 'type' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xingweidong/xwd/envs/python/test38/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/uvicorn/main.py", line 425, in main
    run(app, **kwargs)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/xingweidong/xwd/envs/python/test38/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/xingweidong/xwd/work/xkw/projects/cloud/api/./app/main.py", line 13, in <module>
    logging.config.dictConfig(LOGGING_CONFIG)
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/xingweidong/.pyenv/versions/3.8.14/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'redis_stream'
```

**Comment by Xingwd** [comment]
经过测试分析，发现这个问题是类型注解导致的，可能是python<=3.8版本的类型注解支持不太完善。
解决办法：去掉代码中的类型注解。

该问题在1.0.1中修复。
